config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
 
  
  resources :diaries
  resources :doctors
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params.require(:diary).permit(:name, :date, :emotion)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def index
        @doctors = Doctor.all
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :emotion %>
    <%= form.text_field :emotion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing Diary</h1>
<div  class="u-center-abs ">
<%= render 'form', diary: @diary %>





<button>
<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>
</button>
</div>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h3>🐝 Thoughtfull</h3>

<table class="u-center-abs ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Emotion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.name %></td>
        <td><%= diary.date %></td>
        <td><%= diary.emotion %></td>
        <td><%= link_to 'Show', diary %></td>
        <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
        <td><%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>




<ul>
<li> <%= link_to 'Home', welcome_index_path%>
  <li><%= link_to 'Support', doctors_path %></li>
  <li> <%= link_to 'New Diary', new_diary_path %>
  <li> <%= link_to 'Find a Doctor', doctors_path %>
 
</ul>

app/views/diaries/new.html.erb
<h1>New Journal Entry</h1>



<div class="u-center-abs form">
<%= render 'form', diary: @diary %>

<button> <%= link_to 'Back', diaries_path %> </button
</div>

app/views/diaries/show.html.erb
<div class="container ">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @diary.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @diary.date %>
</p>

<p>
  <strong>Emotion:</strong>
  <%= @diary.emotion %>
</p>

<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>
</div>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Reach out to a Doctor </h4>

<table class="u-center-abs first">
   
        
        <tbody>
        <% @doctors.each do |doctor| %>
            <tr>
            <td><%= doctor.name %></td>
            <td><%= doctor.occupation %></td>
            <td><%= doctor.number %></td>
            <td><%= doctor.location %></td>
            </tr>
            <% end %>
            </tbody>

         </table>

         <br>

         <ul>
<li> <%= link_to 'Home', welcome_index_path%>
  <li><%= link_to 'Journal', diaries_path %></li>
  <li> <%= link_to 'New Diary', new_diary_path %>
  <li> <%= link_to 'Find a Doctor', doctors_path %>
 
</ul>
         

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeelApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Knewave&display=swap" rel="stylesheet">
<h1> 🐝 BEE your best</h1>

<h1><span class="text_1">Welcome 🐝</span>
<span class="text_2"> A Hive to express yourself</span></h1>

<div class="u-center-abs second">
 <button>
<%= link_to 'Begin', diaries_path %> </button>
</div>